### ISSUE TITLE
Feature: Make tabname persist after closing neovim

### ISSUE THREAD

**Issue by sergiornelas** [mg979/tabline.nvim#15]
Hello, could be possible that after renaming the tab persist after you close vim/neovim?
gcmt/taboo.vim has this feature via session:
https://github.com/gcmt/taboo.vim

Thanks.

**Comment by sergiornelas** [comment]
I realized there is already an option for that :Tabline persist, but it has some bugs while using the plugin rmagatti/auto-session.
_auto-session ERROR: Error restoring session! The session might be corrupted._

**Comment by mg979** [comment]
Are you able to load that session with `:source` without errors?

**Comment by sergiornelas** [comment]
yes, no problem. Only has conflict while using **rmagatti/auto-session** plugin.

**Comment by mg979** [comment]
What's your OS and nvim version?

I've seen occasionally errors while sourcing a session, but the session file itself is ok, it's not corrupted. There can be 2 kinds of errors I've seen:
- errors with missing directories so that `cd` commands fail
- with this plugin, I've seen errors from neovim parsing incorrectly the end of the session file

Error 2. is occasional, happens for reasons unknown to me (the actual file is ok), and has no real consequences in loading the session. I should investigate better though.

Anyway that plugin should handle better session errors because an error doesn't mean the file is corrupted, most of the times.

**Comment by mg979** [comment]
Also, you should update the plugin because there has been some work on persistance and I'm not seeing errors right now.

**Comment by sergiornelas** [comment]
I'm using macOS and neovim v0.9.1.

**Comment by sergiornelas** [comment]
The error message is gone but :Tabline persist is not working, the tab name doesn't persist after loading a session via **rmagatti/auto-session**

**Comment by mg979** [comment]
I'll check it out, maybe you can check if it persistence works by loading the session with `:source` and not with the `auto-session` plugin.

**Comment by mg979** [comment]
Ok __gcmt/taboo.vim__ needs

    set sessionoptions+=globals

That's why it works. I can make it work in the same way if the option is set that way, I just didn't want to enforce it, default behaviour is to add the variable in the session file, not to set it in vim. But `auto-session` probably does `mksession!` again, so the variable is lost.

**Comment by mg979** [comment]
You can try this branch

https://github.com/mg979/tabline.nvim/tree/persist_ssop_globals

and see if it works for you. It needs `globals` in `sessionoptions`. I'm a bit skeptical that setting a variable in the session file is a good long term solution, though. If there are often errors while reading the session (because the variable becomes too big) then I'll have to resort to a different method to store persistence, but for the moment this seems to work for small customizations.

**Comment by sergiornelas** [comment]
Still not working, and I have globals in sessionoptions.

**Comment by mg979** [comment]
It works for me, you must enable persistence for the current session with

    :Tabline persist

**Comment by mg979** [comment]
My bad, I was clearing the global variable after updating the session, now it should work.

**Comment by mg979** [comment]
It should work on current master.

**Comment by sergiornelas** [comment]
Yeah, now is working as expected, thanks!
