### ISSUE TITLE
Add more themes

### ISSUE THREAD

**Issue by bellini666** [mg979/tabline.nvim#2]
Hey,

Would be awesome if more themes could be added here. Maybe start with the most popular ones?

I would vote for jellybeans :)

**Comment by mg979** [comment]
I use default myself, because it's adaptive and looks ok with my default color scheme. So I don't know what people like/want. Anyway if you made a theme and want to submit it, feel free.

Theme-making isn't documented yet, but maybe you figured out something on your own. A theme must have a `name`, the highlight groups, and can also have a `settings` member, so that it applies its own settings while it's loaded (changed settings are restored when the theme is unloaded).

Thanks for trying the plugin!

**Comment by bellini666** [comment]
@mg979 np! In the end, since [themer.lua](https://github.com/ThemerCorp/themer.lua) was created I ended up using it. I'm linking this plugin's highlights to theirs (https://github.com/bellini666/dotfiles/blob/master/vim/lua/config/theme.lua#L92)

One thing that might help is to add an integration there, so from one instant to another this plugin will gain support to all themes there!

**Comment by mg979** [comment]
Ok I'll take a look.

**Comment by mg979** [comment]
I added themer support

    :Tabline theme themer

(only working if themer is already loaded).

**Comment by bellini666** [comment]
Many thanks @mg979 . Also, again, thanks for the lib!
